### ISSUE TITLE
Https sorunu

### ISSUE THREAD

**Issue by codesignist** [emirkabal/tcmb-doviz#3]
Merkez bankası adresi Http yerine Https olarak güncellendi
https://github.com/emirkabal/tcmb-doviz/blob/91a1559cbbabc432deddc4178e5471a7d6a99ec4/lib/main.js#L8

**Comment by emirkabal** [comment]
https://github.com/emirkabal/tcmb-doviz/commit/3c19785ad27499ed3db211c1948154e2db7da0c9
