### ISSUE TITLE
Error while on TCMB request.

### ISSUE THREAD

**Issue by uflak** [emirkabal/tcmb-doviz#6]
örnekteki gibi;
```
const data = await tcmbdoviz.getData() // Get All Data
console.log(data)
```
kullanıyorum ve 
'Error while on TCMB request.'
hatası alıyorum

**Comment by emirkabal** [comment]
https://github.com/emirkabal/tcmb-doviz/commit/3c19785ad27499ed3db211c1948154e2db7da0c9
